# Generated by Django 3.1.7 on 2021-04-30 18:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url_slug', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('customer_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.CharField(max_length=255)),
                ('cupon_code', models.CharField(max_length=255)),
                ('discount_amount', models.CharField(max_length=255)),
                ('products_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarchantUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_details', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_slug', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
                ('product_max_price', models.CharField(max_length=255)),
                ('product_discount_price', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_long_description', models.TextField()),
                ('in_total_stock', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsReviews',
            fields=[
                ('product_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_image', models.FileField(upload_to='')),
                ('ratting', models.CharField(default='5', max_length=255)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsVarient',
            fields=[
                ('product_varient_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Merchant'), (4, 'Customer')], default=1, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('SubCategorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url_slug', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.categories')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsVarientItems',
            fields=[
                ('product_varient_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.productsvarient')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTransaction',
            fields=[
                ('product_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_transaction_count', models.IntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[(1, 'BUY'), (2, 'SELL')], max_length=2555)),
                ('transaction_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTags',
            fields=[
                ('product_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsReviewVoting',
            fields=[
                ('product_voting_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('products_views_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.productsreviews')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsQuestions',
            fields=[
                ('product_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField()),
                ('answera', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsMedia',
            fields=[
                ('product_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=255)),
                ('media_content', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField(default=1)),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='SubCategories_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.subcategories'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_added_by_marchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.marchantuser'),
        ),
        migrations.CreateModel(
            name='OrderDeliveryStatus',
            fields=[
                ('order_delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_msg', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDash.customerorders')),
            ],
        ),
        migrations.AddField(
            model_name='marchantuser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='auth_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='products_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AdminDash.products'),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
